#makefile for Project 4

#Compile source code by typing the command make compile
compile:
	javac *.java

#Run SecretDecoder.java by typing the command make run
run:
	java P4Arcade

#Clean the compiled class file by typing the command make clean
clean:
	rm *.class
